-d /home/jordi/Documents/Coding/Github/gowin_stuff/Apple2efpga/tangnano20k/impl/gwsynthesis/tangnano20k.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst /home/jordi/FPGAs/FPGA-Tang20k/GOWIN_HDL/gowin_stuff/Apple2efpga/tangnano20k/src/tangnano20k.cst
-cfg /home/jordi/Documents/Coding/Github/gowin_stuff/Apple2efpga/tangnano20k/impl/pnr/device.cfg
-sdc /home/jordi/FPGAs/FPGA-Tang20k/GOWIN_HDL/gowin_stuff/Apple2efpga/apple2efpga.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
